---
name: "\U0001F41B Bug Report"
description: "If something isn't working as expected \U0001F914"
title: "[Bug]: "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: checkboxes
  id: prerequisites
  attributes:
    label: Prerequisites
    description: Ensure to have completed the submission checklist
    options:
      - label: You read the guidelines for contributing.
        required: true
      - label: You are able to reproduce the problem in the latest version of Sinfonia.
        required: true
      - label: You checked that the problem has not yet been reported (also through closed issues).
        required: true
- type: textarea
  id: step-description
  attributes:
    label: Describe the exact steps to reproduce the problem in as many details as possible
    description: When listing steps, don’t just say what you did, but explain how you did it. 
    placeholder: Tell us what you did to obtain the issue.
  validations:
    required: true
- type: textarea
  id: bug-description
  attributes:
    label: Describe the issue behavior
    description: Describe the behavior you observed after following the steps and point out what exactly is the problem with that behavior.
    placeholder: Tell us what you see.
  validations:
    required: true
- type: input
  id: bitsong-address
  attributes:
    label: BitSong Public Address
    description: Please insert your BitSong public address to guarantee a deeper debug (it is not required, but could help!).
    placeholder: ex. bitsong1...
  validations:
    required: false
- type: input
  id: osmosis-address
  attributes:
    label: Osmosis Public Address
    description: Please insert your Osmosis public address to guarantee a deeper debug (it is not required, but could help!).
    placeholder: ex. osmo1...
  validations:
    required: false
- type: dropdown
  id: browser
  attributes:
    label: Which browser are you using?
    options:
      - Google Chrome
      - Brave
      - Mozilla Firefox
      - Opera
      - Microsoft Edge
      - Safari
      - Other
  validations:
    required: true
- type: input
  id: browser-version
  attributes:
    label: Which is your browser version?
    description: Please, if it is possible try to provide the exact version of the used browser.
    placeholder: ex. 10.0.1
  validations:
    required: false
- type: dropdown
  id: device
  attributes:
    label: Which kind of device are you using?
    options:
      - "Desktop"
      - "Tablet"
      - "Mobile"
  validations:
    required: true
- type: dropdown
  id: ledger
  attributes:
    label: Are you using a ledger?
    options:
      - "Yes"
      - "No"
  validations:
    required: true
- type: input
  id: ledger-version
  attributes:
    label: Which is your ledger version?
    description: Please, if it is possible try to provide the exact version of the used ledger.
    placeholder: ex. 10.0.1
  validations:
    required: false